#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThuHocPhi
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="thuhocphi")]
	public partial class DB_ThuHPDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertuser(user instance);
    partial void Updateuser(user instance);
    partial void Deleteuser(user instance);
    partial void InsertHocKy(HocKy instance);
    partial void UpdateHocKy(HocKy instance);
    partial void DeleteHocKy(HocKy instance);
    partial void Insertdkbldqt(dkbldqt instance);
    partial void Updatedkbldqt(dkbldqt instance);
    partial void Deletedkbldqt(dkbldqt instance);
    #endregion
		
		public DB_ThuHPDataContext() : 
				base(global::ThuHocPhi.Properties.Settings.Default.thuhocphiConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DB_ThuHPDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_ThuHPDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_ThuHPDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_ThuHPDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<user> users
		{
			get
			{
				return this.GetTable<user>();
			}
		}
		
		public System.Data.Linq.Table<HocKy> HocKies
		{
			get
			{
				return this.GetTable<HocKy>();
			}
		}
		
		public System.Data.Linq.Table<dkbldqt> dkbldqts
		{
			get
			{
				return this.GetTable<dkbldqt>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[user]")]
	public partial class user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _username;
		
		private string _password;
		
		private string _HoTen;
		
		private System.Nullable<int> _Phone;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnPhoneChanging(System.Nullable<int> value);
    partial void OnPhoneChanged();
    #endregion
		
		public user()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="Int")]
		public System.Nullable<int> Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HocKy")]
	public partial class HocKy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _HocKyID;
		
		private string _HocKy1;
		
		private System.Nullable<decimal> _HocPhi;
		
		private bool _TrangThai;
		
		private EntitySet<dkbldqt> _dkbldqts;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHocKyIDChanging(int value);
    partial void OnHocKyIDChanged();
    partial void OnHocKy1Changing(string value);
    partial void OnHocKy1Changed();
    partial void OnHocPhiChanging(System.Nullable<decimal> value);
    partial void OnHocPhiChanged();
    partial void OnTrangThaiChanging(bool value);
    partial void OnTrangThaiChanged();
    #endregion
		
		public HocKy()
		{
			this._dkbldqts = new EntitySet<dkbldqt>(new Action<dkbldqt>(this.attach_dkbldqts), new Action<dkbldqt>(this.detach_dkbldqts));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HocKyID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int HocKyID
		{
			get
			{
				return this._HocKyID;
			}
			set
			{
				if ((this._HocKyID != value))
				{
					this.OnHocKyIDChanging(value);
					this.SendPropertyChanging();
					this._HocKyID = value;
					this.SendPropertyChanged("HocKyID");
					this.OnHocKyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="HocKy", Storage="_HocKy1", DbType="VarChar(50)")]
		public string HocKy1
		{
			get
			{
				return this._HocKy1;
			}
			set
			{
				if ((this._HocKy1 != value))
				{
					this.OnHocKy1Changing(value);
					this.SendPropertyChanging();
					this._HocKy1 = value;
					this.SendPropertyChanged("HocKy1");
					this.OnHocKy1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HocPhi", DbType="Money")]
		public System.Nullable<decimal> HocPhi
		{
			get
			{
				return this._HocPhi;
			}
			set
			{
				if ((this._HocPhi != value))
				{
					this.OnHocPhiChanging(value);
					this.SendPropertyChanging();
					this._HocPhi = value;
					this.SendPropertyChanged("HocPhi");
					this.OnHocPhiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Bit NOT NULL")]
		public bool TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HocKy_dkbldqt", Storage="_dkbldqts", ThisKey="HocKyID", OtherKey="HocKyID")]
		public EntitySet<dkbldqt> dkbldqts
		{
			get
			{
				return this._dkbldqts;
			}
			set
			{
				this._dkbldqts.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_dkbldqts(dkbldqt entity)
		{
			this.SendPropertyChanging();
			entity.HocKy = this;
		}
		
		private void detach_dkbldqts(dkbldqt entity)
		{
			this.SendPropertyChanging();
			entity.HocKy = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dkbldqt")]
	public partial class dkbldqt : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSV;
		
		private string _HoTenSV;
		
		private string _MaLop;
		
		private string _NgaySinh;
		
		private System.Nullable<int> _TongSoTC;
		
		private System.Nullable<int> _HocKyID;
		
		private System.Nullable<System.DateTime> _NgayDong;
		
		private string _NguoiThu;
		
		private EntityRef<HocKy> _HocKy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSVChanging(string value);
    partial void OnMaSVChanged();
    partial void OnHoTenSVChanging(string value);
    partial void OnHoTenSVChanged();
    partial void OnMaLopChanging(string value);
    partial void OnMaLopChanged();
    partial void OnNgaySinhChanging(string value);
    partial void OnNgaySinhChanged();
    partial void OnTongSoTCChanging(System.Nullable<int> value);
    partial void OnTongSoTCChanged();
    partial void OnHocKyIDChanging(System.Nullable<int> value);
    partial void OnHocKyIDChanged();
    partial void OnNgayDongChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDongChanged();
    partial void OnNguoiThuChanging(string value);
    partial void OnNguoiThuChanged();
    #endregion
		
		public dkbldqt()
		{
			this._HocKy = default(EntityRef<HocKy>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSV", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSV
		{
			get
			{
				return this._MaSV;
			}
			set
			{
				if ((this._MaSV != value))
				{
					this.OnMaSVChanging(value);
					this.SendPropertyChanging();
					this._MaSV = value;
					this.SendPropertyChanged("MaSV");
					this.OnMaSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTenSV", DbType="NVarChar(200)")]
		public string HoTenSV
		{
			get
			{
				return this._HoTenSV;
			}
			set
			{
				if ((this._HoTenSV != value))
				{
					this.OnHoTenSVChanging(value);
					this.SendPropertyChanging();
					this._HoTenSV = value;
					this.SendPropertyChanged("HoTenSV");
					this.OnHoTenSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLop", DbType="VarChar(50)")]
		public string MaLop
		{
			get
			{
				return this._MaLop;
			}
			set
			{
				if ((this._MaLop != value))
				{
					this.OnMaLopChanging(value);
					this.SendPropertyChanging();
					this._MaLop = value;
					this.SendPropertyChanged("MaLop");
					this.OnMaLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="VarChar(50)")]
		public string NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongSoTC", DbType="Int")]
		public System.Nullable<int> TongSoTC
		{
			get
			{
				return this._TongSoTC;
			}
			set
			{
				if ((this._TongSoTC != value))
				{
					this.OnTongSoTCChanging(value);
					this.SendPropertyChanging();
					this._TongSoTC = value;
					this.SendPropertyChanged("TongSoTC");
					this.OnTongSoTCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HocKyID", DbType="Int")]
		public System.Nullable<int> HocKyID
		{
			get
			{
				return this._HocKyID;
			}
			set
			{
				if ((this._HocKyID != value))
				{
					if (this._HocKy.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHocKyIDChanging(value);
					this.SendPropertyChanging();
					this._HocKyID = value;
					this.SendPropertyChanged("HocKyID");
					this.OnHocKyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDong", DbType="Date")]
		public System.Nullable<System.DateTime> NgayDong
		{
			get
			{
				return this._NgayDong;
			}
			set
			{
				if ((this._NgayDong != value))
				{
					this.OnNgayDongChanging(value);
					this.SendPropertyChanging();
					this._NgayDong = value;
					this.SendPropertyChanged("NgayDong");
					this.OnNgayDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiThu", DbType="NVarChar(200)")]
		public string NguoiThu
		{
			get
			{
				return this._NguoiThu;
			}
			set
			{
				if ((this._NguoiThu != value))
				{
					this.OnNguoiThuChanging(value);
					this.SendPropertyChanging();
					this._NguoiThu = value;
					this.SendPropertyChanged("NguoiThu");
					this.OnNguoiThuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HocKy_dkbldqt", Storage="_HocKy", ThisKey="HocKyID", OtherKey="HocKyID", IsForeignKey=true)]
		public HocKy HocKy
		{
			get
			{
				return this._HocKy.Entity;
			}
			set
			{
				HocKy previousValue = this._HocKy.Entity;
				if (((previousValue != value) 
							|| (this._HocKy.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HocKy.Entity = null;
						previousValue.dkbldqts.Remove(this);
					}
					this._HocKy.Entity = value;
					if ((value != null))
					{
						value.dkbldqts.Add(this);
						this._HocKyID = value.HocKyID;
					}
					else
					{
						this._HocKyID = default(Nullable<int>);
					}
					this.SendPropertyChanged("HocKy");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
